approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmPreapprovedPackages:
  - "@calcit/procs@0.27.0"

packageExtensions:
  "pixi.js@7.2.4":
    dependencies:
      "@pixi/utils": "7.2.4"
